version: 2.1
orbs:
  slack: circleci/slack@3.4.2
workflows:
  version: 2
  build:
    jobs:
    - build
jobs:
  build:
    docker:
      - image: cimg/base:edge-20.04
    resource_class: xlarge
    steps:
      - checkout
      - run: cp -r example-data-sets/* ~/
      - run: |
          echo hello
      - run: |
          # init
          ./init.sh
      - run: |
          # run
          cd graphalytics-1.4.0-duckdb-0.1-SNAPSHOT/
          bin/sh/run-benchmark.sh
